### ISSUE TITLE
Create json for car details and link to js.

### ISSUE THREAD

**Issue by Alok5102R** [Alok5102R/whichcar#13]
Create a separate json file containing all details of car variable in "script.js" and link it to it.

**Comment by yhoungdev** [comment]
can you assign this to me ?

**Comment by Alok5102R** [comment]
Sure @yhoungdev .
Refer to the latest commit before proceeding.

**Comment by Alok5102R** [comment]
Do notify when you start working on it @yhoungdev

**Comment by yhoungdev** [comment]
Starting it now

**Comment by Alok5102R** [comment]
okay

**Comment by Akash88585** [comment]
Can I proceed with this issue?
@Alok5102R

**Comment by Alok5102R** [comment]
@yhoungdev update your status with the issue.
As, other developers are waiting.
