### ISSUE TITLE
Customize the "Choose Car" button

### ISSUE THREAD

**Issue by zugzwang03** [Alok5102R/whichcar#16]
I want to introduce background color flip on the "Choose Car" button on hovering. Like the text is white, and background blue presently, but if we create text as blue and background white on hover, the button feature would be distinctly understandable by the user. Also, a bit of scaling effect may add to smoothness. I want to make this contribution under hacktoberfest'22.

![whichcar](https://user-images.githubusercontent.com/95460021/196397527-dbbfd2ca-1ea9-41d4-84c1-4accc8371f96.png)

**Comment by Alok5102R** [comment]
Sure @zugzwang03 .

**Comment by Alok5102R** [comment]
Cool @zugzwang03
