### ISSUE TITLE
Need auto scrolling effect of car images in home page.

### ISSUE THREAD

**Issue by Alok5102R** [Alok5102R/whichcar#17]
Use "carY.png" , "carZ.png" for this effect including "logoF.png".

**Comment by ELIJAHJOHNNY** [comment]
Hi @Alok5102R  can I go ahead to work on this  or you would prefer to assign to me first?

**Comment by Alok5102R** [comment]
Sure @ELIJAHJOHNNY .
You can proceed .

**Comment by ELIJAHJOHNNY** [comment]
ok! thank you... I'm on it

**Comment by ELIJAHJOHNNY** [comment]
Hi @Alok5102R I am done with the auto scrolling effect and want to push but your ReadMe file says we should add our name to the contributors file before pushing. I really cant find the folder in the repo. Can you kindly help out please?

**Comment by ELIJAHJOHNNY** [comment]
okay! Thanks

**Comment by Alok5102R** [comment]
Thanks @ELIJAHJOHNNY
