### ISSUE TITLE
There's an issue in choose.html price range can't be in negative I would like to fix that

### ISSUE THREAD

**Issue by SukarayamJanjua** [Alok5102R/whichcar#21]

**Comment by Alok5102R** [comment]
Sure @SukarayamJanjua .
You can proceed.

**Comment by Alok5102R** [comment]
@SukarayamJanjua A CSS file already exists in the project. Update your code in that and avoid creation of multiple files.

**Comment by saanvibk** [comment]
@Alok5102R i have fixed negative ranges and added placeholder values for inputs https://github.com/Alok5102R/whichcar/pull/32

**Comment by MemoonaMobeen** [comment]
hey @Alok5102R i would like to contribute to this project
