### ISSUE TITLE
Fixing Mobile view and adding contact section

### ISSUE THREAD

**Issue by s0hamn** [Alok5102R/whichcar#34]
In mobile there is a horizontal scrollbar present which disturbs the UI and also there is no contact us section on the website.
Please assign me so that I can work on it

**Comment by Alok5102R** [comment]
@s0hamn that time website wasn't synced with code.
That's why it was showing that issue.
For checking issue please fork and check locally.

**Comment by Alok5102R** [comment]
As stated, currently we don't require database connection. That's why contact form isn't required.

**Comment by s0hamn** [comment]
sure, thanks

**Comment by Alok5102R** [comment]
Hello @s0hamn .
I just found that horizontal scrollbar issue in mobile view.
You can proceed with the code.
Make changes in "index.html" as well as "choose.html"
Thank you!!

**Comment by s0hamn** [comment]
yes

**Comment by Alok5102R** [comment]
Thanks @s0hamn

**Comment by s0hamn** [comment]
Sure, welcome
