### ISSUE TITLE
Bug: Car Suggestions must be disabled for editing

### ISSUE THREAD

**Issue by AbhiBajpaishek** [Alok5102R/whichcar#36]
The Car suggestions box where all car suggestions are filled in based on filters applied, should not be editable. 

If the issue seems genuine to you as well, please assign this issue to me with the Hacktoberfest label. I can raise a small PR quickly.

**Comment by AbhiBajpaishek** [comment]
PR raised -->

https://github.com/Alok5102R/whichcar/pull/37

**Comment by Alok5102R** [comment]
Thanks @AbhiBajpaishek
