### ISSUE TITLE
Footer missing in mobile view

### ISSUE THREAD

**Issue by Maaz-Code** [Alok5102R/whichcar#43]
Hello there, I noticed that the same footer present in the desktop view was not present in the mobile view. So I would like to add it. If you approve of the idea, kindly assign me this issue. I will then raise the relevant PR. Thank you.

Desktop:

![image](https://user-images.githubusercontent.com/65590762/196780819-f630b7ed-382e-4d2a-a878-07a615000fed.png)

Mobile:

![image](https://user-images.githubusercontent.com/65590762/196780939-10dc18b3-ef5e-4234-84b6-65a95c4ec9f6.png)

**Comment by Priyanshu-su30** [comment]
assign this to me

**Comment by Alok5102R** [comment]
Check correctly, it's visible in all screens.
