### ISSUE TITLE
Redesign Icon

### ISSUE THREAD

**Issue by SSHSRN** [Alok5102R/whichcar#48]
The present icon looks so simple and minimalistic.
![image](https://user-images.githubusercontent.com/62781914/197198027-284827da-192e-4cf2-af74-963ff00df2ee.png)

Kindly assign me this issue so that I can design a better icon for the website

**Comment by Alok5102R** [comment]
You can proceed.
Design gif icon rather than still icon and keep it under 20kb.

**Comment by SSHSRN** [comment]
![image](https://user-images.githubusercontent.com/62781914/197256197-e80eabab-2ad8-43b4-ab8c-13782844906f.png)
does this look good?

**Comment by Alok5102R** [comment]
Make gif @SSHSRN . And keep colour code as (light blue, grey, dark blue, indigo, black)

**Comment by SSHSRN** [comment]
![image](http://www.clipartbest.com/cliparts/Kin/XeM/KinXeMnXT.gif)
How about this?

**Comment by Alok5102R** [comment]
This is cool. Make it's body of white colour. Because site background is black.

**Comment by SSHSRN** [comment]
Ok, and how about this?
![car-logo](https://user-images.githubusercontent.com/62781914/197318173-1173a76d-7c7f-4c87-b709-27e6db88543a.gif)

The dynamic change will also suit the theme of the website.

**Comment by Alok5102R** [comment]
This is also good but make it's outline as blue, so that it'll be visible on site

**Comment by SSHSRN** [comment]
You mean to change the black outline to blue?

**Comment by Alok5102R** [comment]
yes

**Comment by Alok5102R** [comment]
Thanks for your contribution. ❤️
Do [Follow](https://github.com/Alok5102R) 👤 and Star this repository [whichcar](https://github.com/Alok5102R/whichcar) ⭐.
