### ISSUE TITLE
Bug: Content repetition on submitting again

### ISSUE THREAD

**Issue by SSHSRN** [Alok5102R/whichcar#49]
When I specify the requirements and submit the form, it loads up the suggestions as expected. But, when I click on the submit button again, the same content is being displayed again (repetition happens).

I am also attaching a screen recording for your reference.

https://user-images.githubusercontent.com/62781914/197198973-f0486f40-46c0-4f96-94bf-8334b3282cc2.mp4

**Comment by SSHSRN** [comment]
Kindly assign me this issue so that I can work on it!

**Comment by Alok5102R** [comment]
Thanks for finding this issue.
You can proceed on this @SSHSRN

**Comment by Alok5102R** [comment]
This problem is already solved in previous PRs.
Thanks for your participation.
