### ISSUE TITLE
High and low price range

### ISSUE THREAD

**Issue by Alok5102R** [Alok5102R/whichcar#5]
Need to set price range by including high and low range variables.
Update needed in "script.js".

**Comment by Akash88585** [comment]
Can you assign this issue to me?

**Comment by siddhesh-coder** [comment]
plz assign me this issue

**Comment by Alok5102R** [comment]
Sure @Akash88585 
Lemme update high and low fields first in "choose.html".
Thanks for your response @siddhesh-coder , will assign you upcoming issues.

**Comment by Alok5102R** [comment]
I'd updated  "choose.html", now you can proceed @Akash88585 .

**Comment by Alok5102R** [comment]
Thanks @Akash88585
