### ISSUE TITLE
Reset Button Bug on Choose Car page

### ISSUE THREAD

**Issue by vmittal05** [Alok5102R/whichcar#52]
Currently on clicking Reset button only the form values are reset, and the results inside Car Suggestion are not cleared.
Upon executing new query, the results are appended with the older results.
To fully reset the page, user has to reload the page.

@Alok5102R If you are interested I can fix this so that on clicking Reset button all the values inside the Car Suggestion list are cleared as well.

**Comment by Alok5102R** [comment]
It's already fixed @vmittal05 .
Verify with latest commits.
