### ISSUE TITLE
Bug: Page does not reload on clicking submit after changing the constraints

### ISSUE THREAD

**Issue by SSHSRN** [Alok5102R/whichcar#53]
On submitting the form after changing the requirements, sometimes the suggestions fail to load. 

I am attaching a screen recording for your reference.

https://user-images.githubusercontent.com/62781914/197319101-f283d0c9-b9d1-491d-b75a-f4a6f20cb57c.mp4

**Comment by SSHSRN** [comment]
I also identified why this happens. Kindly assign me this issue so that I can work on it.

**Comment by Alok5102R** [comment]
Yes @SSHSRN .
I also noticed that.
You can proceed with this, make your code optimized.
