### ISSUE TITLE
With no filter selected, should display all.

### ISSUE THREAD

**Issue by SardarShubham** [Alok5102R/whichcar#54]
For example, if car type is not been selected, it does not render any output at all. On submit it should return cars of all type having rest of filters.
![Screenshot from 2022-10-23 13-47-02](https://user-images.githubusercontent.com/73052188/197381998-e7d716eb-70aa-4759-802d-549a3350cf50.png)

**Comment by SardarShubham** [comment]
I can solve this problem, assign this task to me under hactoberfest label.

**Comment by Alok5102R** [comment]
Returning all car list will simply create a very big issue @SardarShubham .
