### ISSUE TITLE
If no cars are found, should give proper feedback.

### ISSUE THREAD

**Issue by SardarShubham** [Alok5102R/whichcar#56]
if zero cars are found for given filters. It does not give proper feedback that no results are found and user should update filters.
![Screenshot from 2022-10-23 13-53-54](https://user-images.githubusercontent.com/73052188/197382259-f3df9fb6-4fad-4807-9f29-af0ef83db6c5.png)

**Comment by SardarShubham** [comment]
Assign this task to me.

**Comment by Alok5102R** [comment]
Sure @SardarShubham you can proceed.

**Comment by Alok5102R** [comment]
Thanks @SardarShubham
