### ISSUE TITLE
adding tesla cars to the json

### ISSUE THREAD

**Issue by kasuba97** [Alok5102R/whichcar#57]
to support the climate change forum i have decided to add the tesla models to the JSON file

**Comment by Alok5102R** [comment]
Sure @kasuba97

**Comment by Alok5102R** [comment]
Thanks for your contribution. ❤️
Do [Follow](https://github.com/Alok5102R) 👤 and Star this repository [whichcar](https://github.com/Alok5102R/whichcar) ⭐.
