### ISSUE TITLE
Adding Links to the cars

### ISSUE THREAD

**Issue by grow-xd** [Alok5102R/whichcar#59]
Adding a link to the cars which does not have a link currently

**Comment by grow-xd** [comment]
Please assign this to me

**Comment by Alok5102R** [comment]
@grow-xd add car links (only official links are allowed) as well as add cars range between 10 lakhs to 20 lakhs.

**Comment by grow-xd** [comment]
Done and sent a pr

**Comment by Alok5102R** [comment]
Thanks @grow-xd
