### ISSUE TITLE
Width of the column seems to be big, how about a design change

### ISSUE THREAD

**Issue by the3plet** [Alok5102R/whichcar#61]
![image](https://user-images.githubusercontent.com/88719525/197390992-bd2c04ba-d8e6-4d26-978b-a0e493da350f.png)

What if the size of column is smaller and the aligned the buttons in a attractive manner.
i can work on it, assign me

**Comment by Alok5102R** [comment]
@the3plet 
Design border for this form field with hover and shadow effect.
As well as design heading "Check car" properly.

**Comment by Alok5102R** [comment]
Since, no response.
Need to close it.
