### ISSUE TITLE
Designing the scrollbar

### ISSUE THREAD

**Issue by zugzwang03** [Alok5102R/whichcar#67]
I want to customize the scroll bar to fit it well with the design of the website. Can I make this contribution under hacktoberfest'22?

**Comment by Alok5102R** [comment]
Could you explain scrollbar in which position?

**Comment by zugzwang03** [comment]
![scroll](https://user-images.githubusercontent.com/95460021/197767702-92ac6846-a417-4d6e-962e-aafeb270df62.png)
this one

**Comment by Alok5102R** [comment]
Sure @zugzwang03 
You can proceed.

**Comment by Alok5102R** [comment]
Thanks @zugzwang03
