### ISSUE TITLE
Contact form for queries

### ISSUE THREAD

**Issue by Alok5102R** [Alok5102R/whichcar#72]
Required to add a contact form for user queries.
Without any extra css file or script file.

**Comment by SagarKumar2840** [comment]
Can you assign this to me?
Where we need to link that form?

**Comment by Alok5102R** [comment]
Sure you can proceed @SagarKumar2840 .
Link that form in "choose.html".

**Comment by Alok5102R** [comment]
Thanks @SagarKumar2840
