### ISSUE TITLE
Currency recommendation; usd or eur

### ISSUE THREAD

**Issue by Ns-SheF** [Alok5102R/whichcar#78]
Hi, took a visit to the site. It looks simple at a glance but man... that'll be a lot of data. :cries

A suggestion I'd like to put in: putting the currency in a more globally recognized currency would be better, preferably the USD or EUR. No offense to Lakh, it just gives the idea that the site is curated to be used in India and surroundings - except if that's the intended purpose, then it is okay.

Another alternative might be using language preferences and using symbols for supposed language.

ahhh... now this is not a simple project lol.

**Comment by Alok5102R** [comment]
@Ns-SheF your issue is valid.
Adding a country field in "choose.html" so that currency get update as per region.
Lakhs can be changed to thousand to validate all region.
You can proceed with this.
But, wait for the PR #68 to get resolved.
Then, you can proceed.

**Comment by Ns-SheF** [comment]
Alright. #68 is still open for now. will take a look through an unpublished branch, that way, I think I'll be able to sync without issues when it gets resolved.

**Comment by Alok5102R** [comment]
Ya sure @Ns-SheF

**Comment by Alok5102R** [comment]
Now, you can proceed @Ns-SheF

**Comment by Alok5102R** [comment]
You can proceed now with this issue @Ns-SheF
Fetch the latest commits and begin

**Comment by Alok5102R** [comment]
are you working on it @Ns-SheF ?
