### ISSUE TITLE
As a Developer, I want to improve variable naming in script.js file for better readability

### ISSUE THREAD

**Issue by AbhiBajpaishek** [Alok5102R/whichcar#8]
For starters, variable naming can be improved in the JS logic file. I can change the names of variables so that it gets easier to read code and this could be a first step in improving overall code quality with respect to clean coding metrics.

**Comment by Alok5102R** [comment]
Sure @AbhiBajpaishek .
You can proceed.

**Comment by AbhiBajpaishek** [comment]
@Alok5102R Pls review MR --> 

https://github.com/Alok5102R/whichcar/pull/9.

**Comment by Alok5102R** [comment]
Thanks @AbhiBajpaishek
