### ISSUE TITLE
Fix issue in UI

### ISSUE THREAD

**Issue by Alok5102R** [Alok5102R/whichcar#81]
Issue with footer text in light mode and footer icon in "choose.html".
Add a button "contact us" in "choose.html"

**Comment by DhanushNehru** [comment]
Can you assign this to me @Alok5102R

**Comment by Alok5102R** [comment]
Sure @DhanushNehru .
You can proceed.

**Comment by DhanushNehru** [comment]
Please check @Alok5102R  https://github.com/Alok5102R/whichcar/pull/82

**Comment by DhanushNehru** [comment]
Closed #82 please check https://github.com/Alok5102R/whichcar/pull/84 @Alok5102R
