### ISSUE TITLE
"Car Suggestion" text not visible and UI fixes.

### ISSUE THREAD

**Issue by SardarShubham** [Alok5102R/whichcar#83]
In dark mode, the text is not much visible due to its black color. Also the UI of text can be improved to gain quicker attention.
![Screenshot from 2022-10-30 16-17-05](https://user-images.githubusercontent.com/73052188/198874801-0020e47a-dc57-4923-8bdc-fec9f08e82f7.png)

**Comment by Alok5102R** [comment]
@SardarShubham have a look at it and also change "whichcar" text color in footer in light mode and add contact us button in "choose.html"

**Comment by Alok5102R** [comment]
Thanks @SardarShubham
