### ISSUE TITLE
Login page Addition

### ISSUE THREAD

**Issue by Alok5102R** [Alok5102R/whichcar#87]
Need to add login page with transitions.

**Comment by bhavy03** [comment]
hey @Alok5102R i would like to work on this issue , but could you please provide me further info regarding enhancement of login page.

**Comment by Alok5102R** [comment]
@bhavy03 need to add a login page. With smooth transition on buttons.
Also, email check as well as Password check is required.
Password check: Minimum 8 characters, 1 special character and number.

**Comment by farhanalws4u** [comment]
hi @Alok5102R. If no one is working on this issue then can you please assign this to me so that i start working on this.

**Comment by bhavy03** [comment]
okay @Alok5102R assign it to me i will get it done

**Comment by Alok5102R** [comment]
okay @bhavy03 you can proceed.
Attach screen shot along with PR.
@farhanalws4u will assign you next one sure.

**Comment by Alok5102R** [comment]
okay @bhavy03 you can proceed.
Attach screen shot along with PR.
@farhanalws4u will assign you next one sure.

**Comment by Alok5102R** [comment]
@bhavy03 please update if you are working on this issue.

**Comment by bhavy03** [comment]
yes @Alok5102R i am working on this issue but i will submit pr after 1 oct

**Comment by Alok5102R** [comment]
okay @bhavy03 no issues.

**Comment by Alok5102R** [comment]
Hello  @bhavy03 any update?

**Comment by bhavy03** [comment]
I already submitted pr yesterday

**Comment by Alok5102R** [comment]
you pr is having merge conflicts.
Please, correct them.
And, don't make changes in the main file.
Also, attach the screen shot of the same.

**Comment by Alok5102R** [comment]
Thanks @bhavy03

**Comment by Alok5102R** [comment]
You referred it from your forked commit.
Initiate the pull request, so that I can merge in this repository.
@bhavy03

**Comment by Alok5102R** [comment]
Thanks @bhavy03
