### ISSUE TITLE
Registeration Page Addition

### ISSUE THREAD

**Issue by Alok5102R** [Alok5102R/whichcar#89]
Add registeration page.
Include:
- Name
- Email Id validation
- Password validation: min. 8 characters, 1 digit, 1 symbol
- Password confirmation
- Smooth transition in buttons

**Comment by farhanalws4u** [comment]
may I work on this @Alok5102R

**Comment by Alok5102R** [comment]
sure @farhanalws4u

**Comment by kunalaudichya02** [comment]
I can work on this issue @Alok5102R

**Comment by farhanalws4u** [comment]
Hi @Alok5102R, i have added the UI and validations for the registration page. Is there any api ready that i have to call for user registration ?

**Comment by Alok5102R** [comment]
@farhanalws4u API isn't required yet.
Thanks for adding Login page.
Could you please share screen shot of the same?

**Comment by ombhagwat2401** [comment]
Hello @Alok5102R, I have created registration page for the same with all validations and required fields

Screen shot of page, I can make the UI even better than now...

![Screenshot (742)](https://github.com/Alok5102R/whichcar/assets/144040483/2900c36e-d17e-43e4-a166-9877fab9883a)

Can i pull request??

**Comment by farhanalws4u** [comment]
Hi @Alok5102R , here are the screenshots of my work. I have also added a loader in the button.  
<img width="998" alt="Screenshot 2023-10-01 012416" src="https://github.com/Alok5102R/whichcar/assets/71136605/553eac09-b725-4802-a9cf-bca7e39982fd">
<img width="992" alt="Screenshot 2023-10-01 012443" src="https://github.com/Alok5102R/whichcar/assets/71136605/9493dd40-e3c5-445c-ab29-0f8b6a50b880">

**Comment by farhanalws4u** [comment]
may I create a pull request?

**Comment by farhanalws4u** [comment]
also there is validation in password field that i forget in previous screenshot.

<img width="988" alt="Screenshot 2023-10-01 012443" src="https://github.com/Alok5102R/whichcar/assets/71136605/5218470b-1041-44a8-92be-cef58e5ee41d">

**Comment by Alok5102R** [comment]
sure @farhanalws4u go on

**Comment by Alok5102R** [comment]
Thank you for your contribution @farhanalws4u !!

**Comment by farhanalws4u** [comment]
you are welcome @Alok5102R  and thanks to you for giving me this opportunity.

**Comment by Alok5102R** [comment]
completed.
