### ISSUE TITLE
Proposal to Enhance UI Responsiveness and Add Animations in Contact Form Page

### ISSUE THREAD

**Issue by jaitensahu** [Alok5102R/whichcar#90]
Hii @Alok5102R 
I wanted to discuss an idea that I believe could further elevate the user experience of the contact form. I propose enhancing the UI responsiveness and introducing engaging animations to provide a smoother and more appealing interface.

I'm excited about the opportunity to contribute to this project and look forward to your response.

**Comment by Alok5102R** [comment]
Hi @jaitensahu please proceed.
Also, add cars in background from the images available in repo.
keep image transparency as 30%-40% at choose best position to align.

**Comment by jaitensahu** [comment]
Sure...Thank you

**Comment by jaitensahu** [comment]
Hi @Alok5102R 
updates: 
-> Fixed responsiveness of the page for smaller screens. 
-> Changed font color, and font family to match the design of the home page.

I just wanted to ask if can I use other images of the car other than the images given in the repo..?

**Comment by Alok5102R** [comment]
sure @jaitensahu please proceed.

**Comment by jaitensahu** [comment]
Hii @Alok5102R I have completed my task. Should I create a pull request or will you first merge the two remaining pull requests of others?

**Comment by Alok5102R** [comment]
They are independent @jaitensahu 
You can proceed with the PR.

**Comment by jaitensahu** [comment]
hii @Alok5102R I have created a PR please check and if you find everything ok then please merge it. Also if you want to add anything else please let me know :-)

**Comment by Alok5102R** [comment]
@jaitensahu please mention the PR here and attach screen shot of your enhancement.
Thank you!!

**Comment by jaitensahu** [comment]
Please review the changes in PR #93

Here is a screenshot of the enhancement.
![Screenshot (384)](https://github.com/Alok5102R/whichcar/assets/127736781/3c6a044e-9b3c-484e-ab5e-4a3b758948d2)

**Comment by Alok5102R** [comment]
okay @jaitensahu 
Thank you!!
